import json
import tempfile
import unittest
from pathlib import Path

from tools import compose_hardcoded_string_check


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def write_strings(repo_root: Path) -> None:
    write_text(
        repo_root / "app/src/main/res/values/strings.xml",
        "<resources><string name=\"app_name\">Aura</string></resources>",
    )


def write_screen(repo_root: Path, text: str = "Existing title") -> None:
    write_text(
        repo_root / "app/src/main/java/com/freevibe/ui/ExampleScreen.kt",
        "\n".join(
            [
                "package com.freevibe.ui",
                "",
                "import androidx.compose.material3.Text",
                "",
                "@Composable",
                "fun ExampleScreen() {",
                f"    Text(\"{text}\")",
                "}",
            ]
        ),
    )


class ComposeHardcodedStringCheckTest(unittest.TestCase):
    def test_accepts_current_baseline(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            repo_root = Path(temp_dir)
            baseline_path = repo_root / "docs/localization/hardcoded-string-baseline.json"
            write_strings(repo_root)
            write_screen(repo_root)
            compose_hardcoded_string_check.write_baseline(repo_root, baseline_path)

            result = compose_hardcoded_string_check.validate_baseline(repo_root, baseline_path)

            self.assertEqual(result["status"], "ok")
            self.assertEqual(result["baselineEntries"], 1)
            self.assertEqual(result["currentFindings"], 1)

    def test_rejects_new_hardcoded_text_literal(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            repo_root = Path(temp_dir)
            baseline_path = repo_root / "docs/localization/hardcoded-string-baseline.json"
            write_strings(repo_root)
            write_screen(repo_root)
            compose_hardcoded_string_check.write_baseline(repo_root, baseline_path)
            write_screen(repo_root, "New visible copy")

            with self.assertRaisesRegex(
                compose_hardcoded_string_check.ComposeHardcodedStringError,
                "baseline drifted",
            ):
                compose_hardcoded_string_check.validate_baseline(repo_root, baseline_path)

    def test_rejects_count_increase_for_existing_literal(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            repo_root = Path(temp_dir)
            baseline_path = repo_root / "docs/localization/hardcoded-string-baseline.json"
            write_strings(repo_root)
            write_screen(repo_root)
            compose_hardcoded_string_check.write_baseline(repo_root, baseline_path)
            write_text(
                repo_root / "app/src/main/java/com/freevibe/ui/ExampleScreen.kt",
                "\n".join(
                    [
                        "package com.freevibe.ui",
                        "import androidx.compose.material3.Text",
                        "@Composable",
                        "fun ExampleScreen() {",
                        "    Text(\"Existing title\")",
                        "    Text(\"Existing title\")",
                        "}",
                    ]
                ),
            )

            with self.assertRaisesRegex(
                compose_hardcoded_string_check.ComposeHardcodedStringError,
                "countChanges",
            ):
                compose_hardcoded_string_check.validate_baseline(repo_root, baseline_path)

    def test_rejects_missing_migration_plan(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            repo_root = Path(temp_dir)
            baseline_path = repo_root / "docs/localization/hardcoded-string-baseline.json"
            write_strings(repo_root)
            write_screen(repo_root)
            baseline = compose_hardcoded_string_check.write_baseline(repo_root, baseline_path)
            baseline.pop("migrationPlan")
            baseline_path.write_text(json.dumps(baseline), encoding="utf-8")

            with self.assertRaisesRegex(
                compose_hardcoded_string_check.ComposeHardcodedStringError,
                "migrationPlan",
            ):
                compose_hardcoded_string_check.validate_baseline(repo_root, baseline_path)

    def test_live_baseline_is_valid(self):
        repo_root = Path(__file__).resolve().parents[2]
        baseline_path = repo_root / "docs/localization/hardcoded-string-baseline.json"
        if not baseline_path.exists():
            self.skipTest("live baseline is generated by the implementation batch")

        result = compose_hardcoded_string_check.validate_baseline(repo_root, baseline_path)

        self.assertEqual(result["status"], "ok")


if __name__ == "__main__":
    unittest.main()
